//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discord_guild_channel")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub guild_id: i64,
    #[sea_orm(unique)]
    pub channel_id: i64,
    pub name: String,
    pub position: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord_guild::Entity",
        from = "Column::GuildId",
        to = "super::discord_guild::Column::GuildId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DiscordGuild,
    #[sea_orm(has_many = "super::fleet_category_channel::Entity")]
    FleetCategoryChannel,
}

impl Related<super::discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuild.def()
    }
}

impl Related<super::fleet_category_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategoryChannel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
