//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discord_guild")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub guild_id: String,
    pub name: String,
    pub icon_hash: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discord_guild_channel::Entity")]
    DiscordGuildChannel,
    #[sea_orm(has_many = "super::discord_guild_role::Entity")]
    DiscordGuildRole,
    #[sea_orm(has_many = "super::fleet_category::Entity")]
    FleetCategory,
    #[sea_orm(has_many = "super::ping_format::Entity")]
    PingFormat,
    #[sea_orm(has_many = "super::user_discord_guild::Entity")]
    UserDiscordGuild,
}

impl Related<super::discord_guild_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuildChannel.def()
    }
}

impl Related<super::discord_guild_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuildRole.def()
    }
}

impl Related<super::fleet_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategory.def()
    }
}

impl Related<super::ping_format::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PingFormat.def()
    }
}

impl Related<super::user_discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiscordGuild.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
