//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discord_guild")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub guild_id: i64,
    pub name: String,
    pub icon_hash: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discord_guild_role::Entity")]
    DiscordGuildRole,
}

impl Related<super::discord_guild_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuildRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
