//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fleet_field_value")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub fleet_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub field_id: i32,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fleet::Entity",
        from = "Column::FleetId",
        to = "super::fleet::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Fleet,
    #[sea_orm(
        belongs_to = "super::ping_format_field::Entity",
        from = "Column::FieldId",
        to = "super::ping_format_field::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PingFormatField,
}

impl Related<super::fleet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fleet.def()
    }
}

impl Related<super::ping_format_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PingFormatField.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
