//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fleet_category_channel")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fleet_category_id: i32,
    pub channel_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord_guild_channel::Entity",
        from = "Column::ChannelId",
        to = "super::discord_guild_channel::Column::ChannelId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DiscordGuildChannel,
    #[sea_orm(
        belongs_to = "super::fleet_category::Entity",
        from = "Column::FleetCategoryId",
        to = "super::fleet_category::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FleetCategory,
}

impl Related<super::discord_guild_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuildChannel.def()
    }
}

impl Related<super::fleet_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
