//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fleet_category_access_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fleet_category_id: i32,
    pub role_id: i64,
    pub can_view: bool,
    pub can_create: bool,
    pub can_manage: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord_guild_role::Entity",
        from = "Column::RoleId",
        to = "super::discord_guild_role::Column::RoleId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DiscordGuildRole,
    #[sea_orm(
        belongs_to = "super::fleet_category::Entity",
        from = "Column::FleetCategoryId",
        to = "super::fleet_category::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FleetCategory,
}

impl Related<super::discord_guild_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuildRole.def()
    }
}

impl Related<super::fleet_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
