//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fleet_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub guild_id: String,
    pub ping_format_id: i32,
    pub name: String,
    pub ping_cooldown: Option<i32>,
    pub ping_reminder: Option<i32>,
    pub max_pre_ping: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord_guild::Entity",
        from = "Column::GuildId",
        to = "super::discord_guild::Column::GuildId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DiscordGuild,
    #[sea_orm(has_many = "super::fleet_category_access_role::Entity")]
    FleetCategoryAccessRole,
    #[sea_orm(has_many = "super::fleet_category_channel::Entity")]
    FleetCategoryChannel,
    #[sea_orm(has_many = "super::fleet_category_ping_role::Entity")]
    FleetCategoryPingRole,
    #[sea_orm(
        belongs_to = "super::ping_format::Entity",
        from = "Column::PingFormatId",
        to = "super::ping_format::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PingFormat,
}

impl Related<super::discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuild.def()
    }
}

impl Related<super::fleet_category_access_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategoryAccessRole.def()
    }
}

impl Related<super::fleet_category_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategoryChannel.def()
    }
}

impl Related<super::fleet_category_ping_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategoryPingRole.def()
    }
}

impl Related<super::ping_format::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PingFormat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
