//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fleet")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub category_id: i32,
    pub name: String,
    pub commander_id: String,
    pub fleet_time: DateTimeUtc,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fleet_category::Entity",
        from = "Column::CategoryId",
        to = "super::fleet_category::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FleetCategory,
    #[sea_orm(has_many = "super::fleet_field_value::Entity")]
    FleetFieldValue,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CommanderId",
        to = "super::user::Column::DiscordId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::fleet_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategory.def()
    }
}

impl Related<super::fleet_field_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetFieldValue.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::ping_format_field::Entity> for Entity {
    fn to() -> RelationDef {
        super::fleet_field_value::Relation::PingFormatField.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::fleet_field_value::Relation::Fleet.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
