//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ping_format")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub guild_id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord_guild::Entity",
        from = "Column::GuildId",
        to = "super::discord_guild::Column::GuildId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DiscordGuild,
    #[sea_orm(has_many = "super::fleet_category::Entity")]
    FleetCategory,
    #[sea_orm(has_many = "super::ping_format_field::Entity")]
    PingFormatField,
}

impl Related<super::discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuild.def()
    }
}

impl Related<super::fleet_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategory.def()
    }
}

impl Related<super::ping_format_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PingFormatField.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
