//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ping_format_field")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ping_format_id: i32,
    pub name: String,
    pub priority: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ping_format::Entity",
        from = "Column::PingFormatId",
        to = "super::ping_format::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PingFormat,
}

impl Related<super::ping_format::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PingFormat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
