//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ping_format_field")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ping_format_id: i32,
    pub name: String,
    pub priority: i32,
    pub field_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fleet_field_value::Entity")]
    FleetFieldValue,
    #[sea_orm(
        belongs_to = "super::ping_format::Entity",
        from = "Column::PingFormatId",
        to = "super::ping_format::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PingFormat,
    #[sea_orm(has_many = "super::ping_format_field_value::Entity")]
    PingFormatFieldValue,
}

impl Related<super::fleet_field_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetFieldValue.def()
    }
}

impl Related<super::ping_format::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PingFormat.def()
    }
}

impl Related<super::ping_format_field_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PingFormatFieldValue.def()
    }
}

impl Related<super::fleet::Entity> for Entity {
    fn to() -> RelationDef {
        super::fleet_field_value::Relation::Fleet.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::fleet_field_value::Relation::PingFormatField
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
