//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ping_format_field_value")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ping_format_field_id: String,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ping_format_field::Entity",
        from = "Column::PingFormatFieldId",
        to = "super::ping_format_field::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PingFormatField,
}

impl Related<super::ping_format_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PingFormatField.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
