//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub discord_id: i64,
    pub name: String,
    pub admin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_discord_guild::Entity")]
    UserDiscordGuild,
    #[sea_orm(has_many = "super::user_discord_guild_role::Entity")]
    UserDiscordGuildRole,
}

impl Related<super::user_discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiscordGuild.def()
    }
}

impl Related<super::user_discord_guild_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiscordGuildRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
