//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub discord_id: String,
    pub name: String,
    pub admin: bool,
    pub last_guild_sync_at: DateTimeUtc,
    pub last_role_sync_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fleet::Entity")]
    Fleet,
    #[sea_orm(has_many = "super::user_discord_guild::Entity")]
    UserDiscordGuild,
    #[sea_orm(has_many = "super::user_discord_guild_role::Entity")]
    UserDiscordGuildRole,
}

impl Related<super::fleet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fleet.def()
    }
}

impl Related<super::user_discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiscordGuild.def()
    }
}

impl Related<super::user_discord_guild_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiscordGuildRole.def()
    }
}

impl Related<super::discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_discord_guild::Relation::DiscordGuild.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_discord_guild::Relation::User.def().rev())
    }
}

impl Related<super::discord_guild_role::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_discord_guild_role::Relation::DiscordGuildRole.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_discord_guild_role::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
